DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
  id SERIAL PRIMARY KEY,
  short_code VARCHAR(255) UNIQUE NOT NULL,
  long_url TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
