CREATE TABLE IF NOT EXISTS urls (
  id SERIAL PRIMARY KEY,
  short_url VARCHAR(255) NOT NULL UNIQUE,
  long_url TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL
);

ALTER SEQUENCE urls_id_seq RESTART WITH 1;
